# Generated by Django 4.1.4 on 2022-12-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('etitle', models.CharField(max_length=64)),
                ('eaut', models.CharField(max_length=64)),
                ('edate', models.IntegerField(max_length=64)),
            ],
        ),
    ]
