# Generated by Django 4.1.4 on 2022-12-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('ephone', models.IntegerField()),
                ('eaccount', models.IntegerField()),
                ('eage', models.IntegerField()),
            ],
        ),
    ]
